# Generated by Django 4.2 on 2023-11-23 15:44

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideritem',
            options={'ordering': ['-id'], 'verbose_name': 'Элемент слайдера', 'verbose_name_plural': 'Элементы слайдера'},
        ),
        migrations.AddField(
            model_name='slideritem',
            name='big_image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='big_slider_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Большое изображение'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
        ),
    ]
