# Generated by Django 4.2 on 2023-11-23 15:48

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('app', '0002_alter_slideritem_options_slideritem_big_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='big_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='big_slider_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Большое изображение'),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение'),
        ),
    ]
